---
all:
  children:
    pods:
      children:
        pod1:
          children:
            pod1_spines:
              hosts:
                SP1-P1:    # ✅ Référence directe
                SP2-P1:    # ✅ Pas de sous-dossiers
            pod1_leafs:
              hosts:
                LF1-P1:
                LF2-P1:
            pod1_borderleafs:
              hosts:
                BL1-P1:
                BL2-P1:
        
        pod2:
          children:
            pod2_spines:
              hosts:
                SP1-P2:
                SP2-P2:
            pod2_leafs:
              hosts:
                LF1-P2:
                LF2-P2:
            pod2_borderleafs:
              hosts:
                BL1-P2:
                BL2-P2:
    
    # Groupes globaux par type d'équipement
    spines:
      children:
        pod1_spines:
        pod2_spines:
    
    leafs:
      children:
        pod1_leafs:
        pod2_leafs:
    
    borderleafs:
      children:
        pod1_borderleafs:
        pod2_borderleafs:
    
    # MLAG pairs globaux
    mlag_pairs:
      children:
        mlag_pair_p1_lf:
          hosts:
            LF1-P1:
            LF2-P1:
        mlag_pair_p1_bl:
          hosts:
            BL1-P1:
            BL2-P1: